# kubefs completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_kubefs_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_kubefs_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'lock session toggle'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeconfig' 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    'lock global toggle'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeconfig' 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    'lock session list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock global list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock session set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeconfig' 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    'lock session del'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock session get'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock global set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeconfig' 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    'lock global del'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock global get'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'lock session'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "set toggle del get list")" -- "$cur")
      ;;

    'lock global'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "set toggle del get list")" -- "$cur")
      ;;

    'list-all'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'find'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "kubeauth kubeconfig")" -- "$cur")
      ;;

    'auth'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeauth' 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    'lock'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "global session")" -- "$cur")
      ;;

    'get'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "")" -- "$cur")
      ;;

    'cd'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "$(find "${KUBEFS_ROOT:-$HOME/.kube}" -type f -name '.kubeconfig' -exec dirname {} \; 2>/dev/null | LC_COLLATE=C.UTF-8 sort)")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_kubefs_completions_filter "get list list-all find cd auth lock")" -- "$cur")
      ;;

  esac
} &&
  complete -o nosort -F _kubefs_completions kubefs

# ex: filetype=sh
